# Generated by Django 5.1.2 on 2024-10-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0005_rename_user_type_customuser_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
