# Generated by Django 5.1.2 on 2024-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_category_parent_category_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
