# Generated by Django 5.1.2 on 2024-10-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_category_slug'),
        ('Products', '0007_alter_category_slug'),
    ]

    operations = [
    ]
