# Generated by Django 5.1.2 on 2024-10-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_merge_20241015_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
