# Generated by Django 5.1.2 on 2024-10-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Products', '0010_category_parent_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='Category.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
