# Generated by Django 5.1.2 on 2024-10-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0012_section_alter_brand_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to="products/"),
        ),
    ]
