# Generated by Django 5.1.2 on 2024-10-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0013_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="demo", upload_to="products/"),
            preserve_default=False,
        ),
    ]
